# Generated by Django 3.0.6 on 2020-05-24 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Breed', models.CharField(max_length=20)),
                ('Sex', models.CharField(max_length=20, null=True)),
                ('Color', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.FileField(default='', upload_to='lostList/images/')),
                ('DogNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findmylostpet.Dog')),
            ],
        ),
        migrations.CreateModel(
            name='LostNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20, null=True)),
                ('State', models.CharField(max_length=20, null=True)),
                ('PubDate', models.DateTimeField()),
                ('MissingDate', models.DateTimeField()),
                ('Text', models.TextField()),
                ('Phone', models.CharField(max_length=20, null=True)),
                ('Si', models.CharField(max_length=20, null=True)),
                ('Gu', models.CharField(max_length=20, null=True)),
                ('Dong', models.CharField(max_length=20, null=True)),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FindNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20, null=True)),
                ('State', models.CharField(max_length=20, null=True)),
                ('PubDate', models.DateTimeField()),
                ('MissingDate', models.DateTimeField()),
                ('Text', models.TextField()),
                ('Phone', models.CharField(max_length=20, null=True)),
                ('Si', models.CharField(max_length=20, null=True)),
                ('Gu', models.CharField(max_length=20, null=True)),
                ('Dong', models.CharField(max_length=20, null=True)),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='FindNoticeNum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='findmylostpet.FindNotice'),
        ),
        migrations.AddField(
            model_name='dog',
            name='LostNoticeNum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='findmylostpet.LostNotice'),
        ),
    ]
