# Generated by Django 3.0.6 on 2020-06-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmylostpet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Si', models.CharField(max_length=20, null=True)),
                ('Gu', models.CharField(max_length=20, null=True)),
                ('Dong', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
