# Generated by Django 3.1.1 on 2020-09-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmylostpet', '0003_auto_20200912_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Photo',
            field=models.FileField(default='', upload_to='lostList/images/'),
        ),
    ]
