# Generated by Django 3.1.1 on 2020-10-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmylostpet', '0005_lostnotice_gratuity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='Eye2Ears',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='Eye2Nose',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
