# Generated by Django 3.0.6 on 2020-11-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmylostpet', '0006_auto_20201031_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='Eye2Ears',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='Eye2Nose',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
