# Generated by Django 3.0.6 on 2020-11-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmylostpet', '0007_auto_20201103_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='rep_image_url',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
